#ifndef ASSIGNMENT4CONTROLLER__VISIBILITY_CONTROL_H_
#define ASSIGNMENT4CONTROLLER__VISIBILITY_CONTROL_H_
#if defined _WIN32 || defined __CYGWIN__
  #ifdef __GNUC__
    #define ASSIGNMENT4CONTROLLER_EXPORT __attribute__ ((dllexport))
    #define ASSIGNMENT4CONTROLLER_IMPORT __attribute__ ((dllimport))
  #else
    #define ASSIGNMENT4CONTROLLER_EXPORT __declspec(dllexport)
    #define ASSIGNMENT4CONTROLLER_IMPORT __declspec(dllimport)
  #endif
  #ifdef ASSIGNMENT4CONTROLLER_BUILDING_LIBRARY
    #define ASSIGNMENT4CONTROLLER_PUBLIC ASSIGNMENT4CONTROLLER_EXPORT
  #else
    #define ASSIGNMENT4CONTROLLER_PUBLIC ASSIGNMENT4CONTROLLER_IMPORT
  #endif
  #define ASSIGNMENT4CONTROLLER_PUBLIC_TYPE ASSIGNMENT4CONTROLLER_PUBLIC
  #define ASSIGNMENT4CONTROLLER_LOCAL
#else
  #define ASSIGNMENT4CONTROLLER_EXPORT __attribute__ ((visibility("default")))
  #define ASSIGNMENT4CONTROLLER_IMPORT
  #if __GNUC__ >= 4
    #define ASSIGNMENT4CONTROLLER_PUBLIC __attribute__ ((visibility("default")))
    #define ASSIGNMENT4CONTROLLER_LOCAL  __attribute__ ((visibility("hidden")))
  #else
    #define ASSIGNMENT4CONTROLLER_PUBLIC
    #define ASSIGNMENT4CONTROLLER_LOCAL
  #endif
  #define ASSIGNMENT4CONTROLLER_PUBLIC_TYPE
#endif
#endif  // ASSIGNMENT4CONTROLLER__VISIBILITY_CONTROL_H_
// Generated 15-Nov-2023 20:59:14
// Copyright 2019-2020 The MathWorks, Inc.
